---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-pod
  labels:
    type: db
    author: ch
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mydb-pod
      labels:
        type: db
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ch
