---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      name: php-pod
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: intelliqit/mynew
          ports:
            - containerPort: 90
          resources:
            limits:
              memory: "22Mi"
              cpu: "250m"
            requests:
              memory: "15Mi"
              cpu: "152m"

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  ports:
    - port: 80
  selector:
    run: php-apache
...


