---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    type: appser
spec:
  containers:
    - name: mytomm
      image: tomee
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
