---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nf
  labels:
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key : slave1
              operator: In
              values: 
                - chandu
