---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pc-pod
  labels:
    type: weapp
spec:
  replicas: 2
  template:
    metadata:
      name: http-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: myhttp
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 80
