---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-pod
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: tom-pod
      labels:
        type: db
    spec:
      containers:
        - name: mytom
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 8080
