---
apiVersion: v1
kind: Service
metadata:
  name: http-ser
  labels:
    author: cu
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: proxy
