---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sr
  labels:
    author: ch
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: webapp
