---
apiVersion: v1
kind: Service
metadata:
  name: vote-ser
  labels:
    author: ch
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: vote-app
